import type { CalendarCategory, CalendarViewModel, MonthDay } from "./calendar-types";

const userFact = (detail: string, recordedAt: string) => ({
  label: "Your plan",
  detail,
  recordedAt,
  trustClass: "FACT" as const,
});

const sampleMonthLoads: Record<number, { load: 0 | 1 | 2 | 3 | 4; categories: CalendarCategory[]; landmark?: string }> = {
  1: { load: 1, categories: ["Rest"] },
  2: { load: 2, categories: ["Personal", "Rest"] },
  3: { load: 3, categories: ["Work", "Health"] },
  4: { load: 3, categories: ["Work", "Creator"] },
  5: { load: 3, categories: ["Work", "Learning"] },
  6: { load: 3, categories: ["Work", "Health"] },
  7: { load: 4, categories: ["Work", "Friends"] },
  8: { load: 2, categories: ["Family", "Rest"] },
  9: { load: 2, categories: ["Creator", "Rest"] },
  10: { load: 3, categories: ["Work", "Health"] },
  11: { load: 4, categories: ["Work", "Learning", "Creator"], landmark: "Reel review" },
  12: { load: 4, categories: ["Work", "Health", "Learning"], landmark: "Today" },
  13: { load: 3, categories: ["Work", "Rest"] },
  14: { load: 4, categories: ["Work", "Friends"] },
  15: { load: 3, categories: ["Family", "Friends"], landmark: "Family + friend" },
  16: { load: 2, categories: ["Rest", "Creator"] },
  17: { load: 3, categories: ["Work", "Health"] },
  18: { load: 3, categories: ["Work", "Learning"] },
  19: { load: 3, categories: ["Work", "Creator"] },
  20: { load: 3, categories: ["Work", "Health"] },
  21: { load: 3, categories: ["Work", "Friends"] },
  22: { load: 1, categories: ["Rest"] },
  23: { load: 2, categories: ["Creator", "Personal"] },
  24: { load: 3, categories: ["Work", "Health"] },
  25: { load: 3, categories: ["Work", "Learning"] },
  26: { load: 4, categories: ["Work", "Personal"], landmark: "Appointment" },
  27: { load: 3, categories: ["Work", "Creator"] },
  28: { load: 3, categories: ["Work", "Friends"] },
  29: { load: 2, categories: ["Family", "Rest"] },
  30: { load: 2, categories: ["Creator", "Rest"] },
  31: { load: 3, categories: ["Work", "Health"] },
};

const monthDays: MonthDay[] = Array.from({ length: 31 }, (_, index) => {
  const number = index + 1;
  const entry = sampleMonthLoads[number] ?? { load: 0 as const, categories: [] as CalendarCategory[] };
  return {
    date: `2026-08-${String(number).padStart(2, "0")}`,
    number,
    load: entry.load,
    categories: entry.categories,
    landmark: entry.landmark,
  };
});

export const calendarSample: CalendarViewModel = {
  demoMode: true,
  dateLabel: "Wednesday · 12 August 2026",
  dayTitle: "A workday with a usable evening",
  now: "18:08",
  timezone: "Asia / Kolkata",
  events: [
    {
      id: "work-12",
      date: "2026-08-12",
      startTime: "09:30",
      endTime: "18:00",
      title: "Software job",
      detail: "Primary fixed work block. Today should adapt around it rather than pretend those hours are available.",
      category: "Work",
      commitment: "FIXED",
      status: "COMPLETED",
      origin: "USER",
      source: userFact("Sample structured calendar commitment", "Sample state · 12 Aug 2026"),
    },
    {
      id: "gym-12",
      date: "2026-08-12",
      startTime: "18:30",
      endTime: "19:15",
      title: "Gym",
      detail: "Health time after work. Important, but not treated as evidence for the creator Journey.",
      category: "Health",
      commitment: "IMPORTANT",
      status: "CONFIRMED",
      origin: "USER",
      source: userFact("Sample health plan", "Sample state · 12 Aug 2026"),
    },
    {
      id: "sound-12",
      date: "2026-08-12",
      startTime: "20:15",
      endTime: "21:00",
      title: "Sound learning window",
      detail: "Calendar owns the 45-minute window. Journey owns what was learned, practised, understood, or applied inside it.",
      category: "Learning",
      commitment: "FLEXIBLE",
      status: "CONFIRMED",
      origin: "USER",
      relatedLabel: "Travel Creator / Sound Design",
      source: userFact("Sample learning window", "Sample state · 12 Aug 2026"),
    },
    {
      id: "friend-14",
      date: "2026-08-14",
      startTime: "20:00",
      endTime: "22:00",
      title: "Meet friend",
      detail: "Social time is part of real life, not a productivity failure.",
      category: "Friends",
      commitment: "IMPORTANT",
      status: "TENTATIVE",
      origin: "LIFE_OS_AI",
      source: {
        label: "Life OS interpretation",
        detail: "Prototype interpretation of a conversational plan; not canonical until confirmed",
        recordedAt: "Sample AI routing",
        trustClass: "SUGGESTION",
      },
    },
    {
      id: "family-15",
      date: "2026-08-15",
      startTime: "13:00",
      endTime: "16:00",
      title: "Family lunch",
      detail: "A meaningful fixed life commitment that changes the available shape of Saturday.",
      category: "Family",
      commitment: "FIXED",
      status: "CONFIRMED",
      origin: "USER",
      source: userFact("Sample family commitment", "Sample state · 12 Aug 2026"),
    },
    {
      id: "reel-16",
      date: "2026-08-16",
      startTime: "17:00",
      endTime: "18:30",
      title: "Reel experiment",
      detail: "A flexible creator block linked to Journey evidence without duplicating the reel record here.",
      category: "Creator",
      commitment: "FLEXIBLE",
      status: "TENTATIVE",
      origin: "LIFE_OS_AI",
      relatedLabel: "Travel Creator / Reel experiment",
      source: {
        label: "Life OS proposal",
        detail: "Prototype planning suggestion based on an open Sunday window",
        recordedAt: "Sample AI routing",
        trustClass: "SUGGESTION",
      },
    },
  ],
  week: [
    { date: "2026-08-10", day: "MON", number: "10", occupiedMinutes: 585, openMinutes: 315, dominant: ["Work", "Health"], eventIds: [], note: "work-heavy" },
    { date: "2026-08-11", day: "TUE", number: "11", occupiedMinutes: 630, openMinutes: 270, dominant: ["Work", "Creator", "Learning"], eventIds: [], note: "craft after work" },
    { date: "2026-08-12", day: "WED", number: "12", occupiedMinutes: 600, openMinutes: 300, dominant: ["Work", "Health", "Learning"], eventIds: ["work-12", "gym-12", "sound-12"], note: "today" },
    { date: "2026-08-13", day: "THU", number: "13", occupiedMinutes: 540, openMinutes: 360, dominant: ["Work", "Rest"], eventIds: [], note: "lighter evening" },
    { date: "2026-08-14", day: "FRI", number: "14", occupiedMinutes: 660, openMinutes: 240, dominant: ["Work", "Friends"], eventIds: ["friend-14"], note: "social pressure" },
    { date: "2026-08-15", day: "SAT", number: "15", occupiedMinutes: 300, openMinutes: 600, dominant: ["Family", "Friends"], eventIds: ["family-15"], note: "life day" },
    { date: "2026-08-16", day: "SUN", number: "16", occupiedMinutes: 150, openMinutes: 750, dominant: ["Rest", "Creator"], eventIds: ["reel-16"], note: "open / recover" },
  ],
  month: {
    label: "August 2026",
    days: monthDays,
  },
  year: {
    label: "2026",
    months: [
      { label: "January", short: "JAN", load: 54, categories: ["Work", "Health"], landmark: "restart" },
      { label: "February", short: "FEB", load: 61, categories: ["Work", "Personal"] },
      { label: "March", short: "MAR", load: 58, categories: ["Work", "Health"] },
      { label: "April", short: "APR", load: 66, categories: ["Work", "Family"] },
      { label: "May", short: "MAY", load: 62, categories: ["Work", "Friends"] },
      { label: "June", short: "JUN", load: 57, categories: ["Work", "Rest"] },
      { label: "July", short: "JUL", load: 68, categories: ["Work", "Health", "Creator"], landmark: "creator focus returns" },
      { label: "August", short: "AUG", load: 71, categories: ["Work", "Creator", "Learning"], landmark: "Sound Design active" },
      { label: "September", short: "SEP", load: 28, categories: ["Travel", "Personal"], landmark: "future / not committed" },
      { label: "October", short: "OCT", load: 18, categories: ["Work"] },
      { label: "November", short: "NOV", load: 14, categories: ["Work"] },
      { label: "December", short: "DEC", load: 10, categories: ["Rest", "Travel"] },
    ],
  },
  routedIntents: [
    {
      id: "route-1",
      userWords: "My friend may visit Saturday evening.",
      interpretation: "Possible social plan. Day is known; exact time and certainty are not.",
      destination: "Calendar",
      proposedWhen: "Sat 15 Aug · evening",
      state: "NEEDS_CONFIRMATION",
      reason: "Keep it tentative so it can influence planning without pretending it is confirmed.",
    },
    {
      id: "route-2",
      userWords: "I want to go to Goa next month.",
      interpretation: "Travel interest, not yet a dated commitment.",
      destination: "Travel / NOT NOW",
      state: "ROUTED",
      reason: "Do not block calendar days until intent becomes a real plan or booking.",
    },
    {
      id: "route-3",
      userWords: "I want to learn sound after gym today.",
      interpretation: "Learning intent with a useful time window after an existing health commitment.",
      destination: "Journey + Calendar",
      proposedWhen: "20:15–21:00",
      state: "READY_TO_CONFIRM",
      reason: "Calendar owns the time; Journey owns the learning result and evidence.",
    },
  ],
};
