import type { InteractionChangeTrace } from "../../../packages/contracts/interaction-change-ledger";

export const committedInteractionSample: InteractionChangeTrace = {
  captureId: "capture-sample-committed",
  correlationId: "capture-sample-committed",
  status: "COMMITTED",
  source: {
    authorityClass: "USER_SOURCE",
    actorType: "USER",
    text: "Gym tomorrow at 7",
    occurredAt: "2026-08-13T17:42:00.000Z",
    recordedAt: "2026-08-13T17:42:01.000Z",
    source: "WEB_APP",
  },
  interpretation: {
    authorityClass: "OBSERVATION",
    actorType: "LIFE_OS_AI",
    interpreter: "LIFE_OS_AI",
    intent: "DATED_PLAN",
    certainty: "CONFIRMED",
    confidence: 0.96,
    observations: [
      { id: "time", label: "Timing", value: "An explicit date/time was supplied.", trustClass: "OBSERVATION" },
      { id: "kind", label: "Likely domain", value: "A time-bound Health commitment.", trustClass: "OBSERVATION" },
    ],
    createdAt: "2026-08-13T17:42:02.000Z",
  },
  proposals: [
    {
      proposalId: "proposal-sample-gym",
      authorityClass: "SUGGESTION",
      proposedResultClass: "FACT",
      destination: "CALENDAR",
      operation: "CREATE_CALENDAR_PLAN",
      approvalMode: "REVIEW_AND_APPLY",
      state: "APPLIED",
      summary: "Add Gym to Calendar tomorrow at 19:00.",
      reason: "The Capture contains an explicit time-bound plan suitable for Calendar.",
      createdAt: "2026-08-13T17:42:02.000Z",
      userAction: {
        authorityClass: "DECISION",
        action: "APPROVED",
        actorType: "USER",
        actorId: "user-sample",
        at: "2026-08-13T17:43:00.000Z",
        recordedAt: "2026-08-13T17:43:01.000Z",
      },
      canonicalChange: {
        resultClass: "FACT",
        eventId: "event-sample-calendar-created",
        eventType: "CALENDAR_EVENT_CREATED",
        entityType: "calendar_event",
        entityId: "calendar-sample-gym",
        actorType: "USER",
        actorId: "user-sample",
        source: "WEB_APP",
        occurredAt: "2026-08-13T17:43:00.000Z",
        recordedAt: "2026-08-13T17:43:01.000Z",
        summary: "Calendar event created: Gym",
        details: {
          title: "Gym",
          startsAt: "2026-08-14T19:00:00.000Z",
          endsAt: "2026-08-14T20:00:00.000Z",
          category: "Health",
          commitment: "Important",
        },
      },
    },
  ],
  projectionEffects: {
    status: "NOT_RECORDED_YET",
    items: [],
  },
};

export const rejectedInteractionSample: InteractionChangeTrace = {
  captureId: "capture-sample-rejected",
  correlationId: "capture-sample-rejected",
  status: "CLOSED_NO_CHANGE",
  source: {
    authorityClass: "USER_SOURCE",
    actorType: "USER",
    text: "My friend may visit Saturday evening.",
    occurredAt: "2026-08-13T18:06:00.000Z",
    recordedAt: "2026-08-13T18:06:01.000Z",
    source: "WEB_APP",
  },
  interpretation: {
    authorityClass: "OBSERVATION",
    actorType: "LIFE_OS_AI",
    interpreter: "LIFE_OS_AI",
    intent: "DATED_PLAN",
    certainty: "TENTATIVE",
    confidence: 0.81,
    observations: [
      { id: "certainty", label: "Certainty", value: "The wording is tentative rather than committed.", trustClass: "OBSERVATION" },
      { id: "domain", label: "Likely domain", value: "A possible Friends commitment for Calendar.", trustClass: "OBSERVATION" },
    ],
    clarification: "Should Saturday evening be reserved, or should this remain only a possibility?",
    createdAt: "2026-08-13T18:06:02.000Z",
  },
  proposals: [
    {
      proposalId: "proposal-sample-friend",
      authorityClass: "SUGGESTION",
      proposedResultClass: "FACT",
      destination: "CALENDAR",
      operation: "CREATE_CALENDAR_PLAN",
      approvalMode: "EXPLICIT_CONFIRMATION",
      state: "REJECTED",
      summary: "Reserve a flexible Friends window on Saturday evening.",
      reason: "The plan might need Calendar space, but the Capture does not establish commitment yet.",
      createdAt: "2026-08-13T18:06:02.000Z",
      userAction: {
        authorityClass: "DECISION",
        action: "REJECTED",
        actorType: "USER",
        actorId: "user-sample",
        at: "2026-08-13T18:07:00.000Z",
        recordedAt: "2026-08-13T18:07:01.000Z",
        reason: "Keep Saturday open for now.",
      },
    },
  ],
  projectionEffects: {
    status: "NOT_RECORDED_YET",
    items: [],
  },
};
