import type { TodayViewModel } from "./types";

export const todaySample: TodayViewModel = {
  demoMode: true,
  dateLabel: "Wednesday · 12 August",
  dayPart: "Evening",
  heading: "Your day has shape.",
  orientation: "Work is the fixed base. Protect the body. Use the remaining creative window for one narrow sound experiment.",
  stateLabel: "CONSTRAINED, NOT BLOCKED",
  direction: {
    title: "Build freedom to travel.",
    statement: "Keep financial stability while becoming capable of shooting, directing, editing, and telling stories independently.",
    source: {
      label: "Your decision",
      detail: "Current direction · active structured truth",
      recordedAt: "Confirmed 11 Aug 2026",
      trustClass: "DECISION",
    },
  },
  day: {
    sampleClock: "18:08",
    source: {
      label: "Recorded calendar",
      detail: "Sample calendar state for the design prototype",
      recordedAt: "Demo state",
      trustClass: "FACT",
    },
    items: [
      {
        id: "work",
        time: "09:00",
        endTime: "18:00",
        title: "Software job",
        detail: "Primary work commitment",
        category: "WORK",
        commitment: "FIXED",
        state: "PAST",
        weight: "LONG",
        gapAfter: "30 min open",
      },
      {
        id: "gym",
        time: "18:30",
        endTime: "19:30",
        title: "Gym",
        detail: "Body · training",
        category: "BODY",
        commitment: "IMPORTANT",
        state: "NEXT",
        weight: "MEDIUM",
        gapAfter: "45 min transition",
      },
      {
        id: "sound",
        time: "20:15",
        endTime: "21:00",
        title: "Sound practice",
        detail: "Environmental sound under dialogue",
        category: "CREATOR",
        commitment: "FLEXIBLE",
        state: "LATER",
        weight: "SHORT",
      },
    ],
  },
  focus: [
    { id: "job", label: "Finish work cleanly", reason: "fixed reality", state: "DONE" },
    { id: "body", label: "Train", reason: "body minimum", state: "ACTIVE" },
    { id: "craft", label: "One sound experiment", reason: "current journey", state: "LATER" },
  ],
  creator: {
    journey: "Travel Creator",
    phase: "01 · Sound",
    skill: "Sound Design",
    technique: "Environmental sound",
    intent: "Hear the place as part of the story, not as noise behind it.",
    evidenceStages: [
      { label: "Learned", state: "COMPLETE" },
      { label: "Practised", state: "COMPLETE" },
      { label: "Applied", state: "COMPLETE" },
      { label: "Reviewed", state: "ACTIVE" },
      { label: "Repeated", state: "NEXT" },
    ],
    evidenceCounts: {
      practices: 4,
      reels: 2,
      learnings: 7,
    },
    latestLearning: "An ambient bed feels intentional when it changes with the place instead of staying flat under the entire reel.",
    nextExperiment: "Record one location in three layers: room tone, movement, and one signature detail.",
    source: {
      label: "Your decision",
      detail: "Creator Journey · active phase",
      recordedAt: "Confirmed 11 Aug 2026",
      trustClass: "DECISION",
    },
  },
  suggestion: {
    title: "Keep tonight narrow.",
    body: "Do not add another sound technique tonight. Repeat environmental sound once and review what changed.",
    basis: "The day is already commitment-heavy and Sound Design is the active creator phase. This is guidance, not a decision.",
    source: {
      label: "System suggestion",
      detail: "Prototype reasoning from sample structured state",
      recordedAt: "Generated for this demo",
      trustClass: "SUGGESTION",
    },
  },
  review: {
    label: "LATER TONIGHT",
    title: "Close the day without scoring it.",
    prompt: "What mattered, what moved, and what should tomorrow remember?",
  },
};
