import type { WriteRequestContext } from "../../../packages/domain/write-boundary";
import type {
  SessionVerifier,
  TransportClock,
  TransportRequestIdGenerator,
} from "../../../packages/domain/trusted-transport-auth";

export class AuthenticationRequiredError extends Error {
  constructor() {
    super("Authentication required");
    this.name = "AuthenticationRequiredError";
  }
}

export class AuthenticationUnavailableError extends Error {
  constructor() {
    super("Authentication service unavailable");
    this.name = "AuthenticationUnavailableError";
  }
}

export class TrustedTransportConfigurationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TrustedTransportConfigurationError";
  }
}

export interface UntrustedWebTransportInput {
  credential?: string;
}

export interface TrustedWebRequestContextDependencies {
  sessionVerifier: SessionVerifier;
  clock: TransportClock;
  requestIds: TransportRequestIdGenerator;
}

function requireServerValue(value: string, label: string) {
  if (typeof value !== "string" || !value.trim()) {
    throw new TrustedTransportConfigurationError(`${label} must be generated by the trusted backend`);
  }
}

export async function createTrustedWebRequestContext(
  request: UntrustedWebTransportInput,
  dependencies: TrustedWebRequestContextDependencies,
): Promise<WriteRequestContext> {
  // Capture authoritative transport metadata as soon as the trusted backend receives
  // the request. Authentication may take time, but it must not move receivedAt.
  const receivedAt = dependencies.clock.now();
  const requestId = dependencies.requestIds.next();

  requireServerValue(requestId, "requestId");
  if (!Number.isFinite(Date.parse(receivedAt))) {
    throw new TrustedTransportConfigurationError("receivedAt must be a valid trusted backend timestamp");
  }

  const credential = request.credential;
  if (typeof credential !== "string" || !credential.trim()) {
    throw new AuthenticationRequiredError();
  }

  let verified;
  try {
    verified = await dependencies.sessionVerifier.verify(credential);
  } catch {
    // Provider exceptions are deliberately hidden from the application/client boundary.
    // They can be recorded later through credential-safe security observability.
    throw new AuthenticationUnavailableError();
  }

  if (!verified || typeof verified.userId !== "string" || !verified.userId.trim()) {
    throw new AuthenticationRequiredError();
  }

  return {
    principal: {
      actorType: "USER",
      userId: verified.userId,
    },
    source: "WEB_APP",
    receivedAt,
    requestId,
  };
}
